### ISSUE TITLE
Icon issues ?

### ISSUE THREAD

**Issue by larronni** [jonkristian/wasteplan_trv#1]
Looks like there is a icon issue..
Last week and this week has the same icons, but waste in two weeks has a different icon.... ?
![trv](https://user-images.githubusercontent.com/49139069/81559387-96554b00-938f-11ea-83a9-626c7c73b8d8.jpg)

(Last week it was only one bin that had "blank" icon, the rest was "filled"....)

**Comment by jonkristian** [comment]
Hi, thanks for reporting. Sorry for the late reply, it's been a hectic month.
I will take a look at this at the first opportunity :)

**Comment by jonkristian** [comment]
I've been doing some overhaul on the icons. I've also added more bins and more detailed states. You can now defined `pickup_day` in your sensor. Hope this helps, but also remember, you can customize the sensors if you want :)
