### ISSUE TITLE
Utilgjengelig API

### ISSUE THREAD

**Issue by jonkristian** [jonkristian/wasteplan_trv#13]
Oppretter denne tråden for ordens skyld slik at informasjon ikke blir spredt ut i ulike "Issues".
Som dere kanskje har funnet ut så virker ikke sensorene lenger, dette skyldes at vi ikke lenger har tilgang til Trv api v1.

Jeg har sendt ut noen e-poster for å finne ut om det er mulig å få tilgang til nytt Api v2 som det ser ut til at de har gått over på men responsen var ikke særlig positiv desverre.

`Vi har ikke hatt noe API tilgjengelig, og vi har heller ikke nå noe API du kan få benytte.
Så tviler på at du har benyttet noe API fra oss.`

`Vi har dessverre ikke noe åpnet API for allmenheten, og ei heller planer for dette i nær fremtid.
Men er enig med deg på at vi burde ha det.
Vi får sette det på planen vår i forhold til digitalisering. Vi må bare finne tid til å prioritere dette, og tilgjengeliggjøre dette på en trygg måte.`

Er ikke så mye annet å gjøre enn å vente.

Legger ved @erlendsellie sin [waste-template](https://github.com/erlendsellie/HomeAssistantConfig/blob/master/packages/waste.yaml) som benytter scraping som en mellomløsning, tusen takk Erlend!

**Comment by lasselian** [comment]
Trist. Dette har vært en de mest nyttige integrasjonene jeg til daglig bruker, håper det ordner seg til slutt

**Comment by oyvindhauge** [comment]
Det var utrolig trist. Wasteplan_trv har vært utrolig nyttig @jonkristian, så takk for innsatsen. Jeg kommer til å mase på TRV jeg også, ikke at jeg tror jeg får noe annet svar, meeen.

**Comment by KetilCom** [comment]
Har trv en epost vi kan mase litt på ? Tenker at dess flere det er som etterspør dette så kanskje de ser at de må prioritere å gi oss tilgang til api'et :)

**Comment by jonkristian** [comment]
God idé @KetilCom ! Jeg vet ikke om det hjelper med det hadde jo vært helt supert, kanskje hvis de ser at flere faktisk har stort nytte av API'et. Jeg sendte mail til kildesortering@trv.no og den ble videresendt til noen som svarte meg. 

Ellers vil jeg fremheve @erlendsellie sin [waste-template](https://github.com/erlendsellie/HomeAssistantConfig/blob/master/packages/waste.yaml) som benytter scraping som en mellomløsning, tusen takk Erlend!

**Comment by erlendsellie** [comment]
Bare hyggelig å kunne tilby en mellomløsning @jonkristian :-)

Kunne det vært et alternativ å bruke scrape i denne integrasjonen intill et nytt API er på plass?
Om man foreacher radene i tabellen, intill man har funnet alle søppel-typene, så vil man jo kunne få ca samme funksjonalitet som denne integrasjonen har gitt frem til API'et ble fjernet, med en sensor for hver type søppel.

En 'next pickup' sensor hadde også vært veldig praktisk, isåfall.

**Comment by jonkristian** [comment]
@erlendsellie :) Jo det kunne vært ett alternativ. Jeg satt faktisk og jobbet på en helt ny løsning med config via ui og har brukt en del tid på den (Frem til API'et plutselig en dag ikke var tilgjengelig🗡️), ser jo kanskje at den nye løsningen heller ikke må skrives om så mye for å integrere scrape, så jeg skal vurdere det, akkurat nå sitter jeg med entur kortet så kanskje jeg får ånden over meg når det er ferdig :)

**Comment by strutings** [comment]
Her er svaret jeg fikk fra TRV:

`Hei,
 
Takk for henvendelsen.
Vi undersøker muligheten for et åpent API, og håper å ha en løsning på plass før sommeren.`

**Comment by jonkristian** [comment]
Jøss, det er i såfall veldig gode nyheter :)

**Comment by strutings** [comment]
Ble oppringt av IT- og digitaliseringssjef i TRV i dag. Han ville ha url til APi som ble benyttet med denne integrasjonen. Virker som at utviklerne ikke har informert om at api lå åpent ute 🙈. De har også fått en hel drøss med eposter om samme tema og lurte i samme slengen på om min epost var blitt hacket siden det hadde kommet så mye om dette. Morsom gjeng det her.

**Comment by strutings** [comment]
Håp i hengende snøre. Her er siste svar:

Ser ut som utviklingsselskapet av hjemmesiden til TRV har hatt et API som jeg ikke var klart over.
Vi tar en dialog med de for å se på å få på plass et nytt.

**Comment by KetilCom** [comment]
Hehe. Så da hjalp det å "spamme" de litt da 😁

**Comment by repvik** [comment]
Noe er jo "rett fram" i v2: 
Man kan søke opp UUID til henteadresse med https://trv.no/wp-json/wasteplan/v2/adress/?s=[url-encodet adresse]
Hvordan man får hentet en plan for den UUID'en som ikke må scrapes har jeg ikke funnet ut av enda.

**Comment by larvel** [comment]
Denne informasjonen finnes muligens allerede gjennom appen Tømmeplan Trondheim / Min renovasjon. Kanskjenoen orker å sjekke hvilet api disse bruker?

**Comment by larronni** [comment]
Hørt noe mer fra TRV rundt tilgang på V2 API'et som de plutselig fant? 😄

**Comment by jonkristian** [comment]
@larvel Det er forsøkt ja, men ingen som har klart å finne ut av noe.
@larronni Har desverre ikke hørt noe mer enda nei, men jeg er klar så fort det blir tilgjengelig :-)

**Comment by strutings** [comment]
> Hørt noe mer fra TRV rundt tilgang på V2 API'et som de plutselig fant? 

Fikk melding fra TRV 27.april. Ikke hørt noe etter det. Sendte en epost og ba om status nå nettopp

**Comment by strutings** [comment]
Siste nytt er at rest API skal være på plass i løpet av et par uker. Håp i hengende snøre 🤗

Ser det er flere som ligger i CC på epost, men greit å holde tråden oppdatert også.

**Comment by jonkristian** [comment]
@strutings flott at du holder oss oppdatert, jeg har ikke mottatt noen e-post.

**Comment by larronni** [comment]
Siste skrik fra TRV er at apiet nå er klart, og jeg fikk disse to linkene :

https://trv.no/wp-json/wasteplan/v2/calendar/abf8b2ab-054b-4577-87b3-ebf64fad6b4c?from=2023-01-01&to=2023-12-31

https://trv.no/wp-json/wasteplan/v2/calendar/abf8b2ab-054b-4577-87b3-ebf64fad6b4c

**Comment by erlendsellie** [comment]
Herlig!

**Comment by jonkristian** [comment]
Støtte for API v2 er klar. Integrasjonen bruker nå kalenderen i HA. Må vel regne med at det kan dukke opp problemer, lag  gjerne nye tickets for disse, så lukker jeg denne. :-)
