### ISSUE TITLE
No 'version' key in the manifest file 

### ISSUE THREAD

**Issue by larronni** [jonkristian/wasteplan_trv#3]
WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'wasteplan_trv'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'wasteplan_trv'

**Comment by jonkristian** [comment]
Thanks for reporting. Working on some changes now :)

**Comment by jonkristian** [comment]
Should be fine in latest. Thanks.
