### ISSUE TITLE
Add support for "Containers" and housing association (borettslag).

### ISSUE THREAD

**Issue by Tjomsen** [jonkristian/wasteplan_trv#4]
Firstly, GREAT initiative.
I live in a small flat with housing association containers for trash (which are frequently full...).
I see on their web site that they now have two search fields, with one specifically for housing associations:
![image](https://user-images.githubusercontent.com/81190337/114040474-f09eaa80-9883-11eb-852a-411f5727d86b.png)

 It returns an ID:
![image](https://user-images.githubusercontent.com/81190337/114040523-fd230300-9883-11eb-9bca-e35857371c8f.png)

But this ID seems to not be supported (?) with this repository(whereas a nearby estate home's ID in the same street that I tested with - works well). I don't know if the API doesn't respond to "container" ID's, or if there is a difference in the reply, breaking the interpretation(?), or something completely different.

My expected results should be:
![image](https://user-images.githubusercontent.com/81190337/114040796-41ae9e80-9884-11eb-926a-2940b07d5534.png)

But in Home Assistant, I don't get any error, but "unknown"/"ikke kjent" for all values, except for plant waste :P .
![image](https://user-images.githubusercontent.com/81190337/114040989-6b67c580-9884-11eb-813a-7a3ef0f73535.png)

Any possibility to look into what it would take to add support for housing association "containers"? Not competent at all myself.

Love the idea (and functionality)! Great job!

**Comment by jonkristian** [comment]
Did you extract the bin number as described? Not sure that ID is actually the bin number. Could you look into that first?

**Comment by Tjomsen** [comment]
Hmm. I could not get any direct hits for any variant of my address/borettslag with the link you noted in the readme.
However, when I used the link you posted for my very nearby "reference" estate home. I got an ID, and I got expected results from this repository ( for that house, not mine).

When I went to trv.no and entered my reference home in the leftmost address field, the next page came up with the same ID as your link gave, i.e. trv.no/plan/XXXX

So it does seem like this XXXX is corresponding to the ID that you've used. Off course I cannot know that this is the exact case for container/borettslag-type ID's, but it was my uneducated assumption, since the ID's showed up in that /plan/XXXX address with the same format, etc.

(On a side note, there might have been some change to the returned text of the trv.no address you use in the readme (???) recently, it has parameters such as "P7" and doesn't state bin ID, just ID? I just guessed the ID was what you were after -and it does work, for estate homes. Example response: [{"name":"Flat\u00e5senget","type":"BINS","plan":"P6","calendar":null,"deviations":null,"plans_by_year":{"2020":"P6","2021":"P6"},"id":2260}]    )

**Comment by jonkristian** [comment]
If I'm not mistaken, I think your ID should be 3115, the id in the browser is probably a different one, could you try that one and see?

![image](https://user-images.githubusercontent.com/13219/114267666-5b272600-99fd-11eb-91b3-dc0dd6257985.png)

**Comment by Tjomsen** [comment]
Yes, I have now tried. 

And no, it seems, that the ID in the browser is *the* ID. If you enter trv.no/plan/1160, you get "Nedre flatåsen" which is the correct one (the one I want). 

If I enter trv.no/plan/3115 I get skolevegen (the one you have in your screenshot), which is not the correct housing association.
 
For estate homes, the trv.no/plan/XXXX coincides with the XXXX id field in the link you use in the readme for the same address input. For housing associations/containers, I get no hit from the link in the readme (tried quite a few variants of the name/address), but I do get the trv.no/plan/1160 when I put in the address and select the correct one from the rightmost address field at trv.no/plan.

Hope this helps a bit. I don't fully understand the process, but I am somewhat assuming the 1160 (Nedre Flatås...) is the ID of the container/location.

**Comment by Tjomsen** [comment]
btw: is the "plan: 'P4'"  the day of the week??? or something unrelated?

**Comment by jonkristian** [comment]
I've been looking some more into this and found that you are correct, there are two different types, bins and containers. And containers won't work with my integration. Fortunately there's a way to get containers so I will see about implementing this in the near future.

Not sure about P4 etc ... might be internal plan area ids or something.

**Comment by jonkristian** [comment]
@Tjomsen I can see that for containers the waste gets picked up along with either paper or plastic. In the API waste is combined with both, so technically it's giving us just two sensors, one for `paper, waste` and a second for `plastic, waste`. (Poor API design IMHO).

Though there are two ways to approach this:
- One is to go with the combined method from trv api, it will give you two sensors for those four. This is probably the more correct way.
- The other way is to split, this will give you four sensors like normal, but waste will always be on the same date as the next pickup. But would be neater with it's own icons and description.

Which one do you prefer?

**Comment by Tjomsen** [comment]
@jonkristian 
Wow. Firstly, sorry about replying late. Secondly, fantastic that you are actually looking into this, I'm the only one to bring it up so far, and I am not tech-savvy enough to jump at it myself....

I follow you on the two ways to approach it. Glad to hear you are apparently receiving something for the container types (but that it is bundling waste + one).

I think whatever you decide would be good enough for me and what I want to do...

Pro on the first alternative (two sensors) is maybe the most correct, and matches the actual API response.

I have a small preference on the second one, as it seems to "result" in much the same as the non-container types (i.e. you get the 4 sensors as for non-container types and can view them individually - even if two of the dates would be the same always)...

I would be super-happy with both. Just came to two full paper containers... AGAIN :/

**Comment by jonkristian** [comment]
Hey @Tjomsen!

This was long overdue, sorry about that.

Regarding those two approaches I came to realize that the second one would be adding a little too much unwanted code to achieve, so I opted for the first one, which is more in line with the api. Also thinking that you should be able to create second sensors out of these two that are returned from my integration and apply the customization that you'd like to use. Quite possible to achieve the second too, just a little more work on your end 

I believe the latest update should cover containers now, please update and change the configuration to include `containers: true`.

Feel free to reopen if you experience any issues.

**Comment by jonkristian** [comment]
@Tjomsen In master branch I've changed the code so that it will give you individual sensors.

**Comment by Tjomsen** [comment]
Amazing, thank you!
I will test this next week when my RPi4 arrives and I get the system up and running after some holiday downtime!
