### ISSUE TITLE
device_state_attributes

### ISSUE THREAD

**Issue by larronni** [jonkristian/wasteplan_trv#6]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 10:03:56 (3 occurrences)
Last logged: 10:03:57

Entity sensor.restavfall (<class 'custom_components.wasteplan_trv.sensor.TRVSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.papir (<class 'custom_components.wasteplan_trv.sensor.TRVSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.plastemballasje (<class 'custom_components.wasteplan_trv.sensor.TRVSensor'>) implements device_state_attributes. Please report it to the custom component author.

**Comment by jonkristian** [comment]
@larronni Thanks for reporting! Fixed in 1.0.1 :)
