### ISSUE TITLE
Wrong pickup week

### ISSUE THREAD

**Issue by larronni** [jonkristian/wasteplan_trv#7]
Look like it won't work in 2022... ?

![image](https://user-images.githubusercontent.com/49139069/147848485-0cfbdb10-59d3-4c27-bdb4-1413fa501c9e.png)

![image](https://user-images.githubusercontent.com/49139069/147848522-1d38e359-4380-49cd-aeb1-cbe74c1b1cf1.png)

**Comment by jonkristian** [comment]
I'm not seeing any issues, are you still experiencing this?
If so, please give me some details about your setup.

**Comment by larronni** [comment]
Looks OK now... 
![image](https://user-images.githubusercontent.com/49139069/147938069-f9963956-3b09-4eff-abc6-02217ba4f708.png)
Unsure if it was TRV that needed an update, or it was something with HA... But anyway - everything looks OK now :)
