### ISSUE TITLE
Sensor state formatting

### ISSUE THREAD

**Issue by wallis** [jonkristian/wasteplan_trv#8]
Hey, thanks for maintaining this super useful addon! :)

I see that in your example screenshot the sensor state reads "Om 7 uker", but my sensors read "Uke 6". I never know what week it is, so "Om x uker" would be a lot more useful! Is this configurable somehow, or has it changed since the screenshot was taken?

![image](https://user-images.githubusercontent.com/1766962/151553394-87e9d83d-3cd6-4582-83c1-21256f9c046b.png)

**Comment by jonkristian** [comment]
Totally agree :rofl: I am currently working on a new version and will keep this in mind.

**Comment by jonkristian** [comment]
Fixed in v2.0.0
