### ISSUE TITLE
Wrong week number at end of year

### ISSUE THREAD

**Issue by repvik** [jonkristian/wasteplan_trv#9]
I've set up the integration from scratch, and I noticed these:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/1718917/210139164-5ec15f68-fe0d-4d13-b552-0a25cbfa05ea.png">

I'm hoping TRV isn't gonna wait one year before picking up plast/papir.

**Comment by repvik** [comment]
On sunday, it said "Uke 51" (without "(2023)"):
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/1718917/210240496-ea02d069-d7db-4fe2-9c94-671d0bb71a15.png">

Today it's correct again:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/1718917/210240391-9cce3146-4360-428e-8e43-cf9ee2c83633.png">

**Comment by jonkristian** [comment]
Not sure if this is upstream from the API or a bug, but a new version is being worked on and I will try to investigate.

**Comment by jonkristian** [comment]
Fixed in v2.0.0
